# Generated by Django 4.1.7 on 2023-02-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imgUrl", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="PhotoResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("imgUrl", models.CharField(max_length=500)),
                ("name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
            ],
        ),
    ]
